# Generated by Django 4.0.5 on 2022-06-08 11:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mediatype',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'image'), (2, 'video')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(upload_to='post'),
        ),
    ]
