# Generated by Django 4.0.5 on 2022-06-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Started',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
            ],
        ),
    ]
